"""empty message

Revision ID: 28e2b784640b
Revises: 65886a9b2a76
Create Date: 2018-02-06 18:08:05.542310

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28e2b784640b'
down_revision = '65886a9b2a76'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assessments',
    sa.Column('identifier', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=250), nullable=False),
    sa.Column('scale', sa.Float(), nullable=False),
    sa.Column('coefficient', sa.Integer(), nullable=False),
    sa.Column('precision', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('identifier')
    )
    op.create_index(op.f('ix_assessments_title'), 'assessments', ['title'], unique=True)
    op.create_table('marks',
    sa.Column('identifier', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('coefficient', sa.Integer(), nullable=False),
    sa.Column('_raw', sa.Float(), nullable=True),
    sa.Column('_bonus', sa.Float(), nullable=True),
    sa.Column('assessment_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.identifier'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.identifier'], ),
    sa.PrimaryKeyConstraint('identifier')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('marks')
    op.drop_index(op.f('ix_assessments_title'), table_name='assessments')
    op.drop_table('assessments')
    # ### end Alembic commands ###
