"""empty message

Revision ID: 314a3a516684
Revises: 3228ab9f592a
Create Date: 2018-07-26 15:01:16.702573

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '314a3a516684'
down_revision = '3228ab9f592a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profiles',
    sa.Column('identifier', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('role', sa.String(length=250), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.identifier'], ),
    sa.PrimaryKeyConstraint('identifier')
    )
    op.create_table('profiles__administrators',
    sa.Column('identifier', sa.Integer(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['identifier'], ['profiles.identifier'], ),
    sa.PrimaryKeyConstraint('identifier')
    )
    op.drop_column('users', 'is_superuser')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_superuser', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.drop_table('profiles__administrators')
    op.drop_table('profiles')
    # ### end Alembic commands ###
