"""empty message

Revision ID: 65886a9b2a76
Revises: 9efdc9bb9e1e
Create Date: 2018-02-06 16:53:11.402064

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65886a9b2a76'
down_revision = '9efdc9bb9e1e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('groups',
    sa.Column('identifier', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('identifier')
    )
    op.create_index(op.f('ix_groups_name'), 'groups', ['name'], unique=True)
    op.create_table('students',
    sa.Column('identifier', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('identifier')
    )
    op.create_table('students_groups',
    sa.Column('group', sa.Integer(), nullable=True),
    sa.Column('student', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['group'], ['groups.identifier'], ),
    sa.ForeignKeyConstraint(['student'], ['students.identifier'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('students_groups')
    op.drop_table('students')
    op.drop_index(op.f('ix_groups_name'), table_name='groups')
    op.drop_table('groups')
    # ### end Alembic commands ###
