"""empty message

Revision ID: 6f85c90e5bef
Revises: dc902b4b9ffb
Create Date: 2018-02-14 16:33:34.799068

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f85c90e5bef'
down_revision = 'dc902b4b9ffb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reports',
    sa.Column('identifier', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=250), nullable=False),
    sa.Column('assessment', sa.PickleType(), nullable=True),
    sa.Column('data', sa.PickleType(), nullable=True),
    sa.PrimaryKeyConstraint('identifier')
    )
    op.create_index(op.f('ix_reports_title'), 'reports', ['title'], unique=False)
    op.alter_column('users', 'firstname',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'firstname',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
    op.drop_index(op.f('ix_reports_title'), table_name='reports')
    op.drop_table('reports')
    # ### end Alembic commands ###
