"""empty message

Revision ID: 763af34e14c6
Revises: eec26b900152
Create Date: 2018-07-27 10:34:52.346799

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '763af34e14c6'
down_revision = 'eec26b900152'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rankings',
    sa.Column('identifier', sa.Integer(), nullable=False),
    sa.Column('assessment_id', sa.Integer(), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.identifier'], ),
    sa.ForeignKeyConstraint(['group_id'], ['groups.identifier'], ),
    sa.PrimaryKeyConstraint('identifier')
    )
    op.create_table('ranks',
    sa.Column('identifier', sa.Integer(), nullable=False),
    sa.Column('ranking_id', sa.Integer(), nullable=True),
    sa.Column('mark_id', sa.Integer(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['mark_id'], ['marks.identifier'], ),
    sa.ForeignKeyConstraint(['ranking_id'], ['rankings.identifier'], ),
    sa.PrimaryKeyConstraint('identifier')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ranks')
    op.drop_table('rankings')
    # ### end Alembic commands ###
