"""empty message

Revision ID: 7a3913ccb1cd
Revises: bc0446fdcec3
Create Date: 2018-02-19 15:28:24.482181

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7a3913ccb1cd'
down_revision = 'bc0446fdcec3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reports', sa.Column('assessment_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'reports', 'assessments', ['assessment_id'], ['identifier'])
    op.drop_column('reports', 'assessment')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reports', sa.Column('assessment', mysql.LONGBLOB(), nullable=True))
    op.drop_constraint(None, 'reports', type_='foreignkey')
    op.drop_column('reports', 'assessment_id')
    # ### end Alembic commands ###
