"""empty message

Revision ID: 8f1f81f73632
Revises: 314a3a516684
Create Date: 2018-07-26 15:11:29.687536

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8f1f81f73632'
down_revision = '314a3a516684'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profiles__students',
    sa.Column('identifier', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['identifier'], ['profiles.identifier'], ),
    sa.PrimaryKeyConstraint('identifier')
    )
    op.drop_constraint('marks_ibfk_2', 'marks', type_='foreignkey')
    op.drop_constraint('students_groups_ibfk_2', 'students_groups', type_='foreignkey')
    op.create_foreign_key(None, 'marks', 'profiles__students', ['student_id'], ['identifier'])
    op.create_foreign_key(None, 'students_groups', 'profiles__students', ['student'], ['identifier'])
    op.drop_table('students')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('students_groups_ibfk_2', 'students_groups', type_='foreignkey')
    op.create_foreign_key('students_groups_ibfk_2', 'students_groups', 'students', ['student'], ['identifier'])
    op.drop_constraint('marks_ibfk_2', 'marks', type_='foreignkey')
    op.create_foreign_key('marks_ibfk_2', 'marks', 'students', ['student_id'], ['identifier'])
    op.create_table('students',
    sa.Column('identifier', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('identifier'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.drop_table('profiles__students')
    # ### end Alembic commands ###
