"""empty message

Revision ID: b561ece6157e
Revises: f3d3c454343d
Create Date: 2018-06-20 10:05:41.289091

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b561ece6157e'
down_revision = 'f3d3c454343d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('assessments', 'coefficient', new_column_name='scale', existing_type=sa.Integer())
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('assessments', 'scale', new_column_name='coefficient', existing_type=sa.Integer())
    # ### end Alembic commands ###
