"""empty message

Revision ID: bc0446fdcec3
Revises: 247b927bece4
Create Date: 2018-02-19 14:34:15.168438

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bc0446fdcec3'
down_revision = '247b927bece4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assessments', 'scale')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assessments', sa.Column('scale', mysql.FLOAT(), nullable=False))
    # ### end Alembic commands ###
