"""empty message

Revision ID: dc902b4b9ffb
Revises: 28e2b784640b
Create Date: 2018-02-07 11:26:20.298959

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc902b4b9ffb'
down_revision = '28e2b784640b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'name', nullable=False, server_default=None, new_column_name='lastname', existing_type=sa.String(length=250))
    op.add_column('users', sa.Column('firstname', sa.String(length=250)))
    op.drop_index('ix_users_name', table_name='users')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'lastname', nullable=False, server_default=None, new_column_name='name', existing_type=sa.String(length=250))
    op.create_index('ix_users_name', 'users', ['name'], unique=True)
    op.drop_column('users', 'firstname')
    # ### end Alembic commands ###
