"""empty message

Revision ID: f3d3c454343d
Revises: 3248b7e7ba59
Create Date: 2018-04-21 17:18:42.108588

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f3d3c454343d'
down_revision = '3248b7e7ba59'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assessments', sa.Column('creation_date', sa.DateTime(),
               nullable=False,
               server_default=sa.text('CURRENT_TIMESTAMP')))
    op.add_column('assessments', sa.Column('creator_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'assessments', 'users', ['creator_id'], ['identifier'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'assessments', type_='foreignkey')
    op.drop_column('assessments', 'creation_date')
    op.drop_column('assessments', 'creator_id')
    # ### end Alembic commands ###
