"""empty message

Revision ID: f44c3d800b7a
Revises: 7a3913ccb1cd
Create Date: 2018-02-20 17:52:39.175065

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f44c3d800b7a'
down_revision = '7a3913ccb1cd'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('marks', '_raw', new_column_name='_score', existing_type=sa.Float(), nullable=False)
    op.alter_column('marks', 'coefficient', new_column_name='_scale', existing_type=sa.Integer(), nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('marks', '_score', new_column_name='_raw', existing_type=sa.Float(), nullable=False)
    op.alter_column('marks', '_scale', new_column_name='coefficient', existing_type=sa.Integer(), nullable=False)
    # ### end Alembic commands ###
